MyApp/urls.py
from django.urls import path
from . import views

app_name = 'MyApp'

urlpatterns = [
    path('', views.index, name='index'),
    path('About/', views.about, name='about'),
    path('ComingSoon/', views.comingsoon, name='comingsoon'),      
    path('schedule/create/',views.schedule_create,name ='schedule_create'),
    path('schedule/',views.schedule,name = 'schedule_list'),
    path('schedule/<int:pk>/', views.schedule_detail, name='schedule_detail'),
    path('delete-all', views.schedule_delete,name = 'schedule_delete'),
    path('delete-sel/<id>', views.schedule_delete_selected, name = 'delete_selected'),
]

MyProject/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls import url

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('MyApp.urls')),
]

MyApp/models.py
from django.db import models

# Create your models here.
class Schedule(models.Model):
	tanggal = models.DateField()
	jam = models.TimeField(auto_now_add=False)
	nama_kegiatan = models.CharField(max_length=50)
	tempat = models.CharField(max_length=50)
	kategori = models.CharField(max_length=40)

	def __str__(self):
		return self.nama_kegiatan

MyApp/forms.py
from django import forms
from .models import Schedule
from django.forms import widgets

class Schedule_Form (forms.ModelForm):

    class Meta:
        model = Schedule
        fields = ['nama_kegiatan','tanggal','jam','tempat','kategori']
        widgets = {
            'nama_kegiatan' : forms.Textarea(attrs={'cols': 10, 'rows': 2}),
            'tanggal': forms.DateInput(attrs={'type': 'date'}),
            'jam': forms.TimeInput(attrs={'type': 'time'})}

    def __init__(self, *args, **kwargs):
        super(Schedule_Form,self).__init__(*args, **kwargs)
        for field in self.Meta.fields:
            self.fields[field].widget.attrs.update({
                'class': 'form-control'
            })

MyApp/views.py
from django.shortcuts import render,redirect,get_object_or_404
from django.http import HttpResponse
from .models import Schedule
from .forms import Schedule_Form

# Create your views here.
def index(request):
    return render(request, 'index.html')

def about(request):
    return render(request, 'about.html')

def comingsoon(request):
    return render(request, 'comingsoon.html')

def schedule_create(request):
    if request.method == "POST":
        form = Schedule_Form(request.POST)
        if form.is_valid():
            schedule = form.save(commit=False)
            schedule.save()
            return redirect('schedule_detail', pk=schedule.pk)
    else:
        form = Schedule_Form()
    return render(request, 'schedule.html', {'form': form, })

def schedule_detail(request,pk):
    schedule = Schedule.objects.get(pk=pk)
    return render(request, 'schedule_details.html',{'schedule': schedule,})

def schedule(request):
    schedules = Schedule.objects.all()
    return render(request,'schedule_list.html',{'schedules' : schedules,})

def schedule_delete(request):
    Schedule.objects.all().delete()
    return redirect(schedule)

def schedule_delete_selected(request,id):
    deleted = Schedule.objects.get(id=id)
    deleted.delete()
    return render(request, 'schedule_list.html')

MyApp/templates/about.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
 <meta charset="UTF-8">
 <meta name="viewport" content="width=device-width, initial-scale=1.0,shrink-to-fit=no">
 <meta http-equiv="X-UA-Compatible" content="ie=edge">
 <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
 <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
 <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
 <link rel="stylesheet" href="{% static 'css/style.css' %}">
 <link rel="stylesheet" href="{% static 'css/bootstrap.css' %}">
 <title>About Me</title>
 <link rel="icon" href ="{% static 'images/logo1.png' %}" type="image/x-icon">
</head>
<body>
<nav class="navbar navbar-expand-md sticky-top navbar-dark">
  <a class="navbar-brand" href="{% url 'MyApp:index' %}">
   <img src="{% static 'images/logo1.png' %}" alt="logo web"width="25" height="25" ></a>
   <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="true" aria-label="Toggle navigation">
     <span class="navbar-toggler-icon"></span>
   </button>
  <div class=" sticky collapse navbar-collapse" id="navbarNav">
   <ul class="navbar-nav mr-auto">
    <li class="nav-item active">
      <a class="nav-link" href="{% url 'MyApp:index' %}" style="margin: 0px 10px">Home <span class="sr-only">(current)</span></a>
    </li>
    <li class="nav-item">
     <a class="nav-link" href="#Contact" style="margin: 0px 10px">Contact<span class="sr-only">(current)</span></a>
    </li>
    <li class="nav-item">
     <a class="nav-link" href="{% url 'MyApp:schedule_create' %}" style="margin: 0px 10px">My Schedule<span class="sr-only">(current)</span></a>
    </li>
   </ul>
  </div>
</nav>
 <div class="container-fluid"  id="About">
  <section class="row Sebelahan text-center">
   <div class="col-sm">
    <img src="{% static 'images/stephen2.png' %}" class="img-fluid" alt="IMG_9637" width="100%" height="auto">
   </div>
    <div class="col-sm text-about">
     <h1> Hello, </h1>I’m Stephen. Now I'm an university student who likes
     something that make me happy and something that make someone proud
     of me.I always got some new thing when i study in Universitas Indonesia
     and that makes me want to learn more about it but now, i have to many
     deadline so it's make me puyeng. My Hobby is studying, listen to music,
     and do some work. 
    <br>
    <br>
    <h2 class="hala" style="text-align: right"> About Me</h3>
    </div>
  </section>

  <section class="col Sebelahan" id="Education&Skill"> 
    <div class="col">
     <h1 class="hala"> Education</h1>
     <div class="row">
      <div class="col-sm text-center data">
        <h2 class="text-center h"> University</h2>
         <h4>Universitas Indonesia</h4>
         <br>
         <h2 class="text-center h"> Faculty</h2>
         <h4>Faculty of Computer Science</h4>
      </div>
      <div class="col-sm data text-center">
        <h2 class="text-center h"> High School</h2>
        <h4>SMAK 3 Penabur Jakarta</h4>
      </div>
     </div>
    </div>
    <div class="col">
      <h1 class="hala" style="text-align: right"> My Skill</h1>
      <div class="row data text-center">
       <div class="col-sm  data">
         <h2 class="text-center h">Programming</h2>
         <h4>Java</h4>
         <h4>Python</h4>
         <h4>HTML</h4>
        </div>
        <div class="col-sm text-center data">
         <h2 class="text-center h">Design</h2>
         <h4>Adobe Photoshop</h4>
         <h4>Adobe Illustrato</h4>
         </div>
      </div>
    </div>
</section>

<section class="col Sebelah text-center"id="Contact">
 <blockquote class="text-right quote">
   “Great things
   never came from
   comfort zone”
 </blockquote>
 <div class="row text-center">
 <div class="col-sm text-left" style="margin-bottom: 20px">
   <a href="https://www.instagram.com/stephenhandiar"><img src="{% static 'images/ig.png' %}" class="img-fluid" alt="Self" width="40vh" height= "100%" style="margin-left: 20px;"></a>
   <a href="https://www.linkedin.com/in/stephen-handiar-411ba5184"><img src="{% static 'images/linkedin.png' %}" class="img-fluid" alt="Self" width="40vh" height= "100%" style="margin-left: 20px;"></a>
   <a href="https://line.me/ti/p/~stephen24"><img src="{% static 'images/line.png' %}" class="img-fluid" alt="Self" width="40vh" height= "100%" style="margin-left: 20px;"></a>
   <a href="https://wa.me/083870606710"><img src="{% static 'images/WA.png' %}" class="img-fluid" alt="Self" width="40vh" height= "100%" style="margin-left: 20px;"></a>
 </div>
 <div class="col-sm text-right">
  <img src="{% static 'images/logo4.png' %}" class="img-fluid" alt="Self" width="60vh" height= "100%">
 </div>
 </div>
</section>
 </div>

 <footer class="container-fluid page-footer">  
   <div class=" text-center pt-2">
    <b>-Jangan banyak bergadang, Jangan deadliner, makan yang banyak, istirahat yang banyak-</b>
   </div>
   <div class="footer-copyright text-center pb-2">© 2019 Copyright:
     <a href="{% url 'MyApp:comingsoon' %}"> Stephen Handiar</a>
   </div>
 </footer>
</body>
</html>

MyApp/templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang = "en">
<head>
	<meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
 <link rel="stylesheet" href="{% static 'css/style.css' %}">
 <link rel="stylesheet" href="{% static 'css/bootstrap.css' %}">
	<title>Schedule</title>
 <link rel="icon" href ="{% static 'images/logo1.png' %}" type="image/x-icon">
</head>
<body>
	<div>
		<a href="{% url 'MyApp:schedule_create' %}" class="top-menu"><span class="glyphicon glyphicon-plus"></span></a>
	</div>
    {% block content %}{% endblock %}
</body>
<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
</html>

MyApp/templates/comingsoon.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
 <meta charset="UTF-8">
 <meta name="viewport" content="width=device-width, initial-scale=1.0,shrink-to-fit=no">
 <meta http-equiv="X-UA-Compatible" content="ie=edge">
 <link rel="stylesheet" href="{% static 'css/style.css' %}">
 <link rel="stylesheet" href="{% static 'css/bootstrap.css' %}">
 <title>Coming Soon</title>
 <link rel="icon" href ="{% static 'images/logo1.png' %}" type="image/x-icon">
</head>
<body style="height: 100vh; width :100%;"> 
<div class="bgimg">
  <div class="topleft">
    <a href="{% url 'MyApp:index' %}"><img src="{% static 'images/logo2.png' %}" class="img-fluid" alt="Self" style="width: 10%; height : 10%;"></a>
  </div>
  <div class="middle text-center">
    <h1>COMING SOON</h1>
    <hr>
    <p>- Saat Tidak Sibuk - </p>
  </div>
  <div class="bottomright text-right">
    <p>Penasaran Yaa . .</p>
  </div>
</div>
</body>
</html>

MyApp/templates/index.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
 <meta charset="UTF-8">
 <meta name="viewport" content="width=device-width, initial-scale=1.0,shrink-to-fit=no">
 <meta http-equiv="X-UA-Compatible" content="ie=edge">
 <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
 <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>
 <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>
 <link rel="stylesheet" href="{% static 'css/style.css' %}">
 <link rel="stylesheet" href="{% static 'css/bootstrap.css' %}">
 <title>HomePage</title>
 <link rel="icon" href ="{% static 'images/logo1.png' %}" type="image/x-icon">
</head>
<body id="home" >
 <div class="col-sm"> 
 <div class="row">
   <img src="{% static 'images/logo4.png' %}" class="img-fluid" alt="Self" style="width: 5%; height : 5%;">
   <a href="{% url 'MyApp:about' %}"><button type="button" class="button1" style="right: 35vh;">About Me</button></a>
   <a href="{% url 'MyApp:schedule_list' %}"><button type="button" class="button1" style="right: 10vh;">My Schedule</button></a>
  </div>
  <div class="text-center"style="max-width: 100%;height: auto; position: relative;margin-top:2.5%">
    <img src="{% static 'images/fotowebfix.png' %}" class="img-fluid" alt="Self" style="width: 49%; height : 100%;">
  </div>
 </div>
</body>
</html>

MyApp/templates/schedule.html
{% extends "base.html" %}
<!DOCTYPE html>
<html>
<head>
	<title>Add Schedule</title>
	{% load static %}
 <link rel="icon" href ="{% static 'images/logo1.png' %}" type="image/x-icon">
</head>
<body>
	{% block content %}
	<div class="container col">
		<div class="row " style="margin: 2vh;">
			<div style="margin-right: 20vh">
					<a href="{% url 'MyApp:index' %}"><img src="{% static 'images/logo4.png' %}" class="img-fluid" alt="Self" style="width: auto; height : 9vh;"></a>
				</div>
			<div style="margin-right: 20vh"><h2 style="right:0%;">New Schedule</h2></div>
				<div style="right: 50px;"><a href="{% url 'MyApp:schedule_list' %}"><button type="button" class="button1">See Schedule</button></a></div>
				</div>
			<div class="container">
				<form method="POST" action="{% url 'MyApp:schedule_create' %}">{% csrf_token %}
					 {{ form.as_p }}
						<button type="submit" class="save btn btn-primary">Save</button>		
			 </form>
			</div>
	</div>
	{% endblock %}
</body>
</html>

MyApp/templates/schedule_details.html
{% extends 'base.html' %}
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>Schedule Details</title>
    {% load static %}
 <link rel="icon" href ="{% static 'images/logo1.png' %}" type="image/x-icon">
  </head>
  <body >
    {% block content %}
    <div class="container">
        <div class="container row" style="margin: 2vh;">
            <a href="{% url 'MyApp:index' %}"><div style="margin-right: 10vh"><img src="{% static 'images/logo4.png' %}" class="img-fluid" alt="Self" style="width: auto; height : 9vh;"></a></div>
            <h2>My Detail Schedule</h2>
          </div>
        {% if schedule.tanggal %}
            <div class="white">
                <h2 class="text-center" style="margin-top : 10%;">Kegiatan : {{ schedule.nama_kegiatan }}</h2>
                <h4 class="text-center">{{ schedule.tanggal}} || {{ schedule.jam }} || {{ schedule.tempat }} </h4>
                <a class="delete-all button1" href="{% url 'MyApp:delete_selected' id=schedule.id %}"><button type="button" class="button1">Delete Schedule</button></a>
            </div>  
        {% endif %}
    </div>
{% endblock %}
  </body>
</html>

MyApp/templates/schedule_list.html
{%extends 'base.html'%}
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>My Schedule</title>
    {% load static %}
 <link rel="icon" href ="{% static 'images/logo1.png' %}" type="image/x-icon">
  </head>
  <body>
    <div class="container">
    {% block content %}
    {% if schedules %}
    <div class="container row" style="margin: 2vh;">
        <a href="{% url 'MyApp:index' %}"><div style="margin-right: 10vh"><img src="{% static 'images/logo4.png' %}" class="img-fluid" alt="Self" style="width: auto; height : 9vh;"></a></div>
        <h2>My Schedule</h2>
      </div>
    {% for schedule in schedules %}
        <div class="container white text-center">
            <div style="margin-top:2%;">
                <h2>{{ schedule.nama_kegiatan }}</h2>
                <h4>{{ schedule.tanggal }} || {{ schedule.jam}}</h4>
                <a href="{{ schedule.pk }}">View Details</a>
            </div>
        </div>
    {% endfor %}
    <div class="container row">
      <div class="col">
      <a class="delete-all" href="{% url 'MyApp:schedule_delete' %}"><button type="button" class="button1">Delete All</button></a>
    </div>
    <div class="col">
      <a href="{% url 'MyApp:schedule_create' %}"><button type="button" class="button1">Add Schedule</button></a>
    </div>
    </div>
    {% else %}
    <div class="container row" style="margin: 2vh;">
        <a href="{% url 'MyApp:index' %}"><div style="margin-right: 10vh"><img src="{% static 'images/logo4.png' %}" class="img-fluid" alt="Self" style="width: auto; height : 9vh;"></a></div>
        <h2>My Schedule</h2>
      </div>
    <div class="text-center" style="padding: 2vh">
      <div >
      <h3 class="hi">-Gaada Acara, Seneng deh- </h3>
    </div>
    <div class="col">
      <a href="{% url 'MyApp:schedule_create' %}"><button type="button" class="button1">Add Schedule</button></a>
    </div>
    </div>
  </div>
    {% endif %}
{% endblock %}
  </body>
</html>